version: '3'

services:
    Buservation:
        image: buservation 
        build: .
        restart: unless-stopped
        ports:
            - 8080:8081
        volumes:
            - log-data:/Buservation/Buservation/
                

volumes:
    log-data:
        driver: local
